import {
  Autoformat,
  AutoLink,
  Autosave,
  BalloonToolbar,
  BlockQuote,
  Bold,
  Code,
  CodeBlock,
  Essentials,
  Heading,
  HorizontalLine,
  HtmlEmbed,
  ImageBlock,
  ImageCaption,
  ImageStyle,
  ImageTextAlternative,
  ImageToolbar,
  ImageUpload,
  Italic,
  Link,
  List,
  ListProperties,
  Markdown,
  Paragraph,
  PasteFromMarkdownExperimental,
  PasteFromOffice,
  Strikethrough,
  Table,
  TableCaption,
  TableCellProperties,
  TableColumnResize,
  TableProperties,
  TableToolbar,
  TextTransformation,
  SimpleUploadAdapter,
  type EditorConfig,
} from "ckeditor5";

import { Frontmatter, FrontmatterToolbar } from "@witoso/ckeditor5-frontmatter";

// Static editor configuration; the per-instance autosave handler is
// added in the Editor component.
export const editorConfig: EditorConfig = {
  licenseKey: "GPL",
  plugins: [
    Autosave,
    Essentials,
    Frontmatter,
    FrontmatterToolbar,
    Autoformat,
    AutoLink,
    BalloonToolbar,
    BlockQuote,
    Bold,
    Code,
    CodeBlock,
    Heading,
    HorizontalLine,
    HtmlEmbed,
    ImageBlock,
    ImageCaption,
    ImageStyle,
    ImageTextAlternative,
    ImageToolbar,
    ImageUpload,
    Italic,
    Link,
    List,
    ListProperties,
    Markdown,
    Paragraph,
    PasteFromMarkdownExperimental,
    PasteFromOffice,
    Strikethrough,
    Table,
    TableCaption,
    TableCellProperties,
    TableColumnResize,
    TableProperties,
    TableToolbar,
    TextTransformation,
    SimpleUploadAdapter,
  ],
  balloonToolbar: [
    "bold",
    "italic",
    "|",
    "link",
    "|",
    "bulletedList",
    "numberedList",
  ],
  toolbar: [
    "undo",
    "redo",
    "|",
    "frontmatter",
    "|",
    "heading",
    "|",
    "bold",
    "italic",
    "strikethrough",
    "code",
    "|",
    "link",
    "uploadImage",
    "insertTable",
    "blockQuote",
    "codeBlock",
    "htmlEmbed",
    "|",
    "bulletedList",
    "numberedList",
  ],
  ui: {
    poweredBy: {
      position: "inside",
      side: "right",
      verticalOffset: -10,
      horizontalOffset: 0,
      label: "Powered by",
    },
  },
  image: {
    toolbar: [
      "toggleImageCaption",
      "imageTextAlternative",
      "|",
      "imageStyle:alignBlockLeft",
      "imageStyle:block",
      "imageStyle:alignBlockRight",
    ],
    styles: {
      options: ["alignBlockLeft", "block", "alignBlockRight"],
    },
  },
  simpleUpload: {
    uploadUrl: "/api/upload",
  },
  link: {
    addTargetToExternalLinks: true,
    defaultProtocol: "https://",
  },
  list: {
    properties: {
      styles: true,
      startIndex: true,
      reversed: true,
    },
  },
  placeholder: "Type or paste your content here!",
  table: {
    contentToolbar: [
      "tableColumn",
      "tableRow",
      "mergeTableCells",
      "tableProperties",
      "tableCellProperties",
    ],
  },
};
